### ISSUE TITLE
Webpack 5 Support

### ISSUE THREAD

**Issue by jandreola** [damorej-at-theinstitutes/webpack-concat-files-plugin#15]
This library doesn't work in Webpack 5, they dropped the api `compilation.fileTimestamps` in favor of using `compilation.fileSystemInfo`. 
Unfortunately Webpack 5 documentation is a bit vague on how to switch one with another.

**Comment by joe-damore** [comment]
Hi @jandreola, thanks for the report! I'll take a closer look and try to have a fix for this published soon.

**Comment by demilsson** [comment]
Would it be possible to release these changes please?

**Comment by damorej-at-theinstitutes** [comment]
@demilsson @jandreola Sorry for the delay getting this together! I'm hoping to release this later today, maybe tomorrow at the latest. Just had to fix a few last minute issues.

**Comment by damorej-at-theinstitutes** [comment]
Just published v0.5.0 with Webpack 5 support. Not seeing it on npmjs.com yet, but was able to install it via `npm install` so it should be available to anybody who needs it. Thank you!
