### ISSUE TITLE
transforms.after, throws error as it returns a promise.

### ISSUE THREAD

**Issue by bc-50** [damorej-at-theinstitutes/webpack-concat-files-plugin#22]
Plugin itself is fine just your example is a bit off. Using webpack 5, your transform example didn't work for me as "terser.minify(code)" returns a promise so an error would be thrown. To fix I awaited the promise first. so the end result looks like this.
new WebpackConcatPlugin({
      bundles: [{
        src: "./src/js/*.js",
        dest: "./dist/bundle.js",
        transforms: {
          after: async (code) => {
            var minicode = await terser.minify(code);
            return minicode.code;
          },
        },
      }],
    }),
    You may want to update the example.

**Comment by damorej-at-theinstitutes** [comment]
Great catch, thank you @bc-50! I'll update that example soon.

**Comment by damorej-at-theinstitutes** [comment]
That example is now fixed, and I'll be publishing a new version of the package on NPM later today with that improvement included.

I'm going to close this issue now. Thanks again for reporting, @bc-50!
